### ISSUE TITLE
finish theeyetribe eye tracker integration

### ISSUE THREAD

**Issue by isolver** [isolver/psychopy#19]
- [ ] add built in calibration support
- [ ] add device config settings that are needed (if any)
- [ ] talk with company about any developments on calculating accurate sample by sample delays.
